language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: Rs7heEyWmYFGum24LntxSJFDhHtKuy7aV2pYIhp46Qqs5BPgup794F70IU1uJL/dYiD9rhJHs9jJ5K66bdavK+hRuLcpUwEV+sQCRYL0nljZ7G0XsC76053sWnYNpSBhGIB1wXdAxLZtG4wBrocmCMWGQ1mXL6coWh/ejOxmgQvdeXT6CbQfAWBTzTVsP9XYvHGcXBukUn60tigm2PAPW4e889aHV8fRcamatlxjlXDCN7i1ctzypPcITX/IB4jeIOtf/IkCG5rrsCN3RDfFA/uC5t+iZ8uoA49llIU0Lith7NaAD4VevD+UYTYUqujMfhsP8QxBxTL3BKJjv+jVbg2a0bBxEzK9BZtflNA7QoeX10Sfpu1DpxgTT0UHWRilEClLPnRKzwsxTdSZ26RLuJMQYwzez5U7xYT94fS1WR7nTsIZiT3s/8R0sFxBNb2bIJyBxxMO5niwONl7mjMIPapstajrMB5yR0Rqc8YZC21caUgnyqpSBM0B3jPK4fxfDEkz0uXHU7OvnRgM9Wx5E3vpZhTvhre+Wzwc1OSbDmcx89SoMNPqIMUL2M2MFUYLiskhP33cL/U7IjLo/hIOGPp9xkcyYv3SmrtUpwKZlcYemG17y8TsQvSXh4s3Yr2xSYPv5o07tyEjFKfyy9r+oaGNG8qvas2tEUGrl0Lf1Kw=
