language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: NKZdTBXLEVnbHdzZCjjIFyuO04quAjchRKdcKWmGAm3Uu5dQsG79HKp1l8s6tR1K/TyRo5EpoUaVOrJO8YoVEDfbajje3dbl9a8lKjjA2M7+qvl72+6IOibV5qsxxbyU0LrtcP97FZclXbqYvNLynuD16Bc0muek2bYrREgs+7tJ8+V2KTzGh+Uuz8uSuMhDKd+SdEsaMVj8BJOPoBCQEoDsYSlTPlekuhaxBgTETW8hewKovB+9o59wUMuSCVEbtYiO4kJzyn0sbqwTuhvPUizv+N/vIIyBjUv1L8LEbXqBFkyai095IYEmGykd/S32lHscNehWSf7x+6QGUJlDFOdl6Ch4C4azW6frYc6TDqQsiw6bz55yPl4v8HaJlxLv6mzj3DSFVVBB8wj2Y+LbW1ME+6TiX78P71AlI3R7qjRrCffzoTwwJfxf5EY4G+yMZIiszcH48rGUu/O8jrFfpEKaVWGav6pC8yju3n3KWBCa4wOEcNW0gkts+z9/D18oqm+K42+JoCDqQUGLXbjCe45zcv8VHbGxX+IITvp7PJmcKFI+Fr0q0NbZly4LV8+dcVHj1/nTx33jOQLmwzoN0vbZA9XqE5dRaSoq0cgZEackXvr6i2aPPuJZQqbO6qIkTf4v+/RCveSElAYKyFDTHCmBBgQln47/OJ6w6WlKnMw=
